# Generated by Django 4.2.10 on 2024-02-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
