# Generated by Django 4.2.10 on 2024-02-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0002_rename_name_contact_password_remove_contact_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='name',
        ),
    ]
