# Generated by Django 4.2.10 on 2024-02-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0003_rename_password_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=122)),
                ('password', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=122),
        ),
    ]
