# Generated by Django 4.2.10 on 2024-02-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0004_logindetails_alter_contact_email_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetails',
            old_name='email',
            new_name='username',
        ),
    ]
