# Generated by Django 4.2.10 on 2024-02-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0005_rename_email_logindetails_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='branchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=122)),
                ('section', models.IntegerField(default=0, max_length=122)),
            ],
        ),
    ]
