# Generated by Django 4.2.10 on 2024-02-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0006_branchdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdetails',
            name='sub_section',
            field=models.IntegerField(default=0, max_length=122),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='section',
            field=models.CharField(default='', max_length=122),
        ),
    ]
