# Generated by Django 4.2.10 on 2024-03-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0007_branchdetails_sub_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchdetails',
            name='sub_section',
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='section',
            field=models.IntegerField(default=0, max_length=122),
        ),
    ]
