# Generated by Django 4.2.5 on 2024-03-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0009_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
