# Generated by Django 4.2.5 on 2024-03-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0010_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourNewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
