# Generated by Django 4.2.5 on 2024-03-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0011_yournewtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_element', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_element', models.CharField(max_length=100)),
                ('main_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studease.maintable')),
            ],
        ),
    ]
