# Generated by Django 4.2.5 on 2024-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0012_maintable_subtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtable',
            name='sub_element_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtable',
            name='sub_element_9',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subtable',
            name='sub_element',
            field=models.CharField(default='', max_length=100),
        ),
    ]
