# Generated by Django 4.2.5 on 2024-03-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0013_subtable_sub_element_1_subtable_sub_element_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='branchDetails',
        ),
        migrations.DeleteModel(
            name='YourNewTable',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AlterField(
            model_name='maintable',
            name='main_element',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='maintable',
            name='subsection_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studease.subsection'),
        ),
    ]
