# Generated by Django 4.2.5 on 2024-03-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0014_subsection_delete_branchdetails_delete_yournewtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='subsection_table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studease.subsection'),
        ),
    ]
