# Generated by Django 4.2.5 on 2024-03-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0015_alter_maintable_subsection_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginDetails',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='subsection_table',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='subsection',
        ),
        migrations.AddField(
            model_name='maintable',
            name='main_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studease.subsection'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='main_subsection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='main_element',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subtable',
            name='main_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studease.maintable'),
        ),
    ]
