# Generated by Django 4.2.5 on 2024-03-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0017_rollnumber_timetable_remove_subtable_main_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='roll_number',
        ),
        migrations.DeleteModel(
            name='RollNumber',
        ),
        migrations.DeleteModel(
            name='subsection',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
