# Generated by Django 4.2.5 on 2024-03-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0018_remove_timetable_roll_number_delete_rollnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_section_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studease.rollnumber')),
            ],
        ),
        migrations.AddField(
            model_name='rollnumber',
            name='sub_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studease.subsection'),
        ),
    ]
