# Generated by Django 4.2.5 on 2024-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0019_rollnumber_subsection_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollnumber',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
