# Generated by Django 4.2.5 on 2024-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0020_rollnumber_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollnumber',
            name='subsection',
            field=models.CharField(default='', max_length=100),
        ),
    ]
