# Generated by Django 4.2.5 on 2024-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0022_remove_rollnumber_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollnumber',
            name='roll_number',
            field=models.IntegerField(max_length=100),
        ),
    ]
