# Generated by Django 4.2.5 on 2024-03-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0023_alter_rollnumber_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.AddField(
            model_name='timetable',
            name='friday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='monday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sub_section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='studease.subsection'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thrusday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tuesday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wednesday',
            field=models.CharField(default='', max_length=100),
        ),
    ]
