# Generated by Django 4.2.5 on 2024-03-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0024_remove_timetable_class_name_remove_timetable_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='thrusday',
            new_name='thursday',
        ),
    ]
