# Generated by Django 4.2.5 on 2024-03-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0025_rename_thrusday_timetable_thursday'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfeedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackfirstname', models.CharField(max_length=100)),
                ('feedbacklastnamme', models.CharField(max_length=100)),
                ('feedbackemail', models.CharField(max_length=100)),
                ('feedbackmessage', models.CharField(max_length=100)),
            ],
        ),
    ]
