# Generated by Django 4.2.5 on 2024-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0026_userfeedbacktable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='roll_number',
        ),
    ]
