# Generated by Django 4.2.5 on 2024-03-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0027_remove_timetable_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedbacktable',
            old_name='feedbacklastnamme',
            new_name='feedbacklastname',
        ),
    ]
