# Generated by Django 4.2.5 on 2024-03-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0028_rename_feedbacklastnamme_userfeedbacktable_feedbacklastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='newtime',
            field=models.TimeField(default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sub_section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='studease.subsection'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
