# Generated by Django 4.2.5 on 2024-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0029_timetable_newtime_alter_timetable_sub_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacantvenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('p1', models.IntegerField(max_length=100)),
                ('p2', models.IntegerField(max_length=100)),
                ('p3', models.IntegerField(max_length=100)),
                ('p4', models.IntegerField(max_length=100)),
                ('p5', models.IntegerField(max_length=100)),
                ('p6', models.IntegerField(max_length=100)),
                ('p7', models.IntegerField(max_length=100)),
                ('p8', models.IntegerField(max_length=100)),
                ('p9', models.IntegerField(max_length=100)),
                ('p10', models.IntegerField(max_length=100)),
            ],
        ),
    ]
